version: '3.8'

services:
    student-management-system:
        depends_on:
            - mongo
            - mongo-express
        container_name: StudentManagementSystem
        image: student-management-system
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - _MONGO_HOST=mongo
        networks:
            - student-management-system-network

    mongo:
        container_name: mongodb
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: none
        ports:
            - "8082:27017"
        networks:
            - student-management-system-network

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: none
            ME_CONFIG_MONGODB_URL: mongodb://root:none@mongo:27017
        networks:
            - student-management-system-network

networks:
    student-management-system-network:
        driver: bridge
