server:
    port: 8080

logging:
    level:
        org:
            springframework: INFO
        graphql: INFO
        graphql.execution: INFO
        graphql.execution.instrumentation: INFO
        graphql.execution.preparsed: INFO
        graphql.execution.strategy: INFO
        graphql.execution.value: INFO
        graphql.schema.idl: INFO

security:
    jwt:
        expiration-time: 86400000
        refresh-time: 604800000
        encoding-key: 25442A472D4B6150645367566B597033733676397924423F4528482B4D625165

spring:
    graphql:
        schema:
            file-extensions:
                - .graphql
                - .graphqls
        graphiql:
            enabled: true
    data:
        mongodb:
            username: root
            password: none
            authentication-database: admin
            database: sms
            port: 8082
            host: ${_MONGO_HOST}
